<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>



<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>訂貨明細</title>

<link rel="stylesheet" href="../css/table.css" />
<style type="text/css">
<!--
.style2 {font-size: small}
#form2 {
}
#apDiv1 {
	position:absolute;
	left:544px;
	top:438px;
	width:248px;
	height:46px;
	z-index:1;
}
-->
</style>
<link href="bg_color" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
.style4 {color: #666666}
#apDiv2 {
	position:absolute;
	left:13px;
	top:60px;
	width:40px;
	height:32px;
	z-index:2;
}
#apDiv3 {
	position:absolute;
	left:14px;
	top:61px;
	width:40px;
	height:18px;
	z-index:2;
}
-->
</style><!--
<script type="text/javascript" src="../js/jquery.js"></script>
-->


</head><body>
<form id="counterOrderDetailForm1" name="counterOrderDetailForm1" method="post" action="">
  <span class="style2">&nbsp; 訂貨專櫃</span>  
  <label>: <span class="style2 style4"> 新加坡 / 北區 / SOGO櫃 / 柯以敏</span></label>
</form>
<table border="0" cellpadding="0" cellspacing="0" width="734">
  <tbody><tr><td><div class="style2" align="center">
  <table align="center" border="1" bordercolor="#cccccc" cellpadding="0" cellspacing="0" width="765">
    <tbody><tr>
      <td rowspan="1" class="tableHead2" width="42"><!--全選-->
        <input name="selectall" id="selectall" type="checkbox" />
      </td>
      <td rowspan="1" class="tableHead2" width="33">項次</td>
      <td rowspan="1" class="tableHead2" width="76">貨號</td>
      <td rowspan="1" class="tableHead2" width="50">顏色</td>
      <td rowspan="1" colspan="1" class="tableHead3">
            <div align="center">065<br />
SML<br />
024<br />
            </div>
</td><td rowspan="1" colspan="1" class="tableHead3">
            <div align="center">070<br />
MDM<br />
026<br />
            </div>
            </td>
            <td rowspan="1" colspan="1" class="tableHead3">
            <div align="center">075<br />
LRG<br />
028<br />
            </div>
            </td>
            <td rowspan="1" colspan="1" class="tableHead3">
            <div align="center">080<br />
ELG<br />
030<br />
            </div>
            </td>
            <td colspan="1" rowspan="1" class="tableHead3">
            <div align="center">085<br />
QLG<br />
032<br />
            </div>
            </td>

      <td rowspan="1" class="tableHead2" width="64">小計</td>
      <td rowspan="1" class="tableHead2" width="64">修改單號</td>
      <td rowspan="1" class="tableHead2">備註</td>
    </tr>
    <tr>
      
      
      
      
      
    </tr>
    <tr>
      <td class="style2" bgcolor="#ddeeff"><label>
        
              </label><div align="center">
                <input name="checkbox" id="checkbox" type="checkbox" />
                </div>
            </td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center">1</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr>
      <td>
        
            <div align="center">
              <input name="checkbox2" id="checkbox2" type="checkbox" />
              </div></td>
      <td><div class="style2" align="center">2</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr>
      <td bgcolor="#ddeeff">
        
            <div align="center">
              <input name="checkbox3" id="checkbox3" type="checkbox" />
              </div></td>
      <td bgcolor="#ddeeff"><div class="style2" align="center">3</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr>
      <td>
        
            <div align="center">
              <input name="checkbox4" id="checkbox4" type="checkbox" />
              </div></td>
      <td><div class="style2" align="center">4</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr bgcolor="#7dbeff">
      <td bgcolor="#ddeeff">
        
            <div align="center">
              <input name="checkbox5" id="checkbox5" type="checkbox" />
              </div></td>
      <td bgcolor="#ddeeff"><div class="style2" align="center">5</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr>
      <td>
        
            <div align="center">
              <input name="checkbox6" id="checkbox6" type="checkbox" />
              </div></td>
      <td><div class="style2" align="center">6</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr bgcolor="#7dbeff">
      <td bgcolor="#ddeeff">
        
            <div align="center">
              <input name="checkbox7" id="checkbox7" type="checkbox" />
              </div></td>
      <td bgcolor="#ddeeff"><div class="style2" align="center">7</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr>
      <td>
        
            <div align="center">
              <input name="checkbox8" id="checkbox8" type="checkbox" />
              </div></td>
      <td><div class="style2" align="center">8</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr bgcolor="#7dbeff">
      <td bgcolor="#ddeeff">
        
            <div align="center">
              <input name="checkbox9" id="checkbox9" type="checkbox" />
              </div></td>
      <td bgcolor="#ddeeff"><div class="style2" align="center">9</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>

    <tr>
      <td>
        
            <div align="center">
              <input name="checkbox11" id="checkbox11" type="checkbox" />
              </div></td>
      <td><div class="style2" align="center">10</div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r1" id="r1" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r2" id="r2" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r3" id="r3" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r4" id="r4" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r5" id="r5" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r6" id="r6" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r7" id="r7" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r8" id="r8" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r9" id="r9" value="" size="5" maxlength="5" type="text" /></div></td>
      <td class="style2" bgcolor="#ddeeff"><div class="style2" align="center"><input name="r10" id="r10" value="" size="10" maxlength="40" type="text" /></div></td>
    </tr>
    <tr>
      <td rowspan="1" colspan="4" class="tableHead">合計</td><td colspan="1" style="vertical-align: top;"><br />
            </td>
            <td colspan="1" style="vertical-align: top;"><br />
            </td>
            <td colspan="1" style="vertical-align: top;"><br />
            </td>
            <td colspan="1" style="vertical-align: top;"><br />
            </td>
            <td style="vertical-align: top;"><br />
            </td>

      <td align="center">&nbsp;</td>
      <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
      <td class="tableHead2">備<br/>註</td>
      <td colspan="11">
        <textarea cols="62" rows="2" name="remark">&nbsp;</textarea>
      </td>
      </tr>
  </tbody></table>
</div></td>
  </tr>
</tbody></table>
</body></html>
